# Generated by Django 2.1.2 on 2018-10-20 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=18)),
                ('title', models.CharField(max_length=50)),
                ('hometown', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
